### ISSUE TITLE
大佬，文本内容包括一些正常词汇的，也被当敏感词给过滤了

### ISSUE THREAD

**Issue by Orangeices** [Disguiser-D/ai_platform_1#1]
!(https://user-images.githubusercontent.com/51935112/158953862-176af454-fcb5-4658-8002-889c4e925b19.png)

**Comment by Disguiser-D** [comment]
使用dfa算法进行敏感词过滤比较依赖于词库 虽然可以通过丰富词库和改良匹配规则进行解决 但毕竟治标不治本 敏感词过滤最好的方法还是使用深度学习比较稳妥 日后可能会加入基于深度学习的敏感词过滤方法

**Comment by Orangeices** [comment]
> 使用dfa算法进行敏感词过滤比较依赖于词库 虽然可以通过丰富词库和改良匹配规则进行解决 但毕竟治标不治本 敏感词过滤最好的方法还是使用深度学习比较稳妥 日后可能会加入基于深度学习的敏感词过滤方法

感谢回复！还想请教一下，如果用深度学习的话，是要做语义识别、情感分析之类的吧？

**Comment by Disguiser-D** [comment]
是的
